MOBILE_CLIENT/IOS/_INFO/IPA_PLIST_FILES/meta.json
Update outdated Reference for the Priority list files entry.
=> Update Reference for the Priority list files entry

MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/description.md, MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/meta.json, MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
=> XPath injection kb entry

MOBILE_CLIENT/COMMON/_IMPORTANT/PACKAGE_OBFUSCATED/description.md, MOBILE_CLIENT/COMMON/_IMPORTANT/PACKAGE_OBFUSCATED/meta.json, MOBILE_CLIENT/COMMON/_IMPORTANT/PACKAGE_OBFUSCATED/recommendation.md
There was a typo in the folder name.
=> Fix typo in flutter obfuscated package entry

MOBILE_CLIENT/COMMON/_HIGH/CORS_MISCONFIGURATION/description.md, MOBILE_CLIENT/COMMON/_HIGH/CORS_MISCONFIGURATION/meta.json, MOBILE_CLIENT/COMMON/_HIGH/CORS_MISCONFIGURATION/recommendation.md, MOBILE_CLIENT/COMMON/_HIGH/LEAKING_PERSONAL_INFORMATION/meta.json
Add CORS misconfiguration entry.
=> Add CORS misconfiguration entry

WEB_SERVICE/WEB/_MEDIUM/WEB_XSS/description.md, WEB_SERVICE/WEB/_MEDIUM/WEB_XSS/recommendation.md
there is no meta.json in this PR because I didn't change it
=> Update xss KB entry

MOBILE_CLIENT/IOS/_HIGH/IPA_INSECURE_PRIVACY_MANIFEST_FILE/recommendation.md
=> Fix Missing privacy manifest file xml part.

MOBILE_CLIENT/ANDROID/_SECURE/APK_CHECK_ROOT/meta.json, MOBILE_CLIENT/ANDROID/_SECURE/APK_DEBUG_SECURE/meta.json, MOBILE_CLIENT/ANDROID/_SECURE/APK_INSECURE_NETWORK_SECURITY_CONFIG_SECURE/meta.json, MOBILE_CLIENT/COMMON/_SECURE/PRIVACY_POLICY_PERSONAL_DATA_CATEGORIES_PROPER_DISCLOSURE/meta.json, MOBILE_CLIENT/COMMON/_SECURE/THIRDPARTY_SHARING_INFORMATION_IN_PRIVACY_POLICY_PRESENT/meta.json, MOBILE_CLIENT/IOS/_SECURE/IPA_SECURE_PRIVACY_MANIFEST_FILE/meta.json, MOBILE_CLIENT/IOS/_SECURE/PRIVACY_NO_SENSITIVE_DATA_OUTSIDE_APP_CONTAINER/meta.json
Removing categories from secure findings as they should not count in the standards report.
=> Multiple KB entry fixes.

.github/workflows/pytest.yaml, tests/test-requirements.txt
- Integrated code coverage checks into the workflow using Codecov.
---
This enhancement introduces several benefits to the project:
1. **Automated Code Coverage Reporting**: 
- A bot will automatically provide a code coverage percentage for each new PR.
- Example:
2. **Detailed Annotations**:
- New annotations on PRs to highlight coverage details.
- Example:
3. **Additional Checks**:
- Two extra checks will be added to each new PR:
- **Project Check**: Ensures the overall codebase coverage percentage is maintained by comparing with the main branch.
- **Patch Check**: Assesses the coverage of the current changes in the PR.
- Example:
---
- **Optional Merges**: Codecov checks are optional for merging a PR. This is because sometimes the Codecov API can fail, and we don't want to block the …
=> Integration of Code Coverage Checks with Codecov

.github/workflows/pytest.yaml, .github/workflows/typing_checker.yaml
Updated workflow(s), pip to uv, files changed:
- `typing_checker.yaml`  
- `pytest.yaml`
=> Updates KB workflow(s), pip to uv.

WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_RP/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_RP/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_RP/recommendation.md
Secure web http referrer policy KB
=> Secure web http referrer policy

WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HEADER/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HEADER/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HEADER/recommendation.md
Secure HTTP header settings KB
=> Secure HTTP header settings

WEB_SERVICE/WEB/_SECURE/SECURE_WEB_COOKIE_FLAGS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_WEB_COOKIE_FLAGS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_WEB_COOKIE_FLAGS/recommendation.md
=> Secure web cookie flags

WEB_SERVICE/WEB/_SECURE/SECURE_CROSS_ORIGIN_RESOURCE_SHARING/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_CROSS_ORIGIN_RESOURCE_SHARING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_CROSS_ORIGIN_RESOURCE_SHARING/recommendation.md
Secure Cross-Origin Resource Sharing KB
=> Secure Cross-Origin Resource Sharing

WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HSTS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HSTS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HSTS/recommendation.md
Secure HTTP Strict Transport Security KB
=>  Secure HTTP Strict Transport Security

WEB_SERVICE/WEB/_HARDENING/WEB_HTTP_CSP/meta.json, WEB_SERVICE/WEB/_HARDENING/WEB_HTTP_HSTS/recommendation.md, WEB_SERVICE/WEB/_LOW/WEB_HTTP_HEADER/description.md, WEB_SERVICE/WEB/_LOW/WEB_HTTP_HEADER/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_HTTP_HSTS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_WEB_COOKIE_FLAGS/description.md
- Add references and description to insecure header settings KB
- Add references to Insecure HTTP Header Setting: (CSP) KB
- Fix Secure Cookies KB description
- Update recommendation in Insecure HTTP Strict Transport Security
=> Fix Insecure Web KBs

WEB_SERVICE/WEB/_HIGH/OUTDATED_SSL_PROTOCOL/description.md, WEB_SERVICE/WEB/_HIGH/OUTDATED_SSL_PROTOCOL/meta.json, WEB_SERVICE/WEB/_HIGH/OUTDATED_SSL_PROTOCOL/recommendation.md
Outdated SSL/TLS Protocols Supported KB.
=>   Outdated SSL/TLS Protocols Supported KB.

WEB_SERVICE/WEB/_HIGH/TLS_FALLBACK_SCSV_NOT_SUPPORTED/description.md, WEB_SERVICE/WEB/_HIGH/TLS_FALLBACK_SCSV_NOT_SUPPORTED/meta.json, WEB_SERVICE/WEB/_HIGH/TLS_FALLBACK_SCSV_NOT_SUPPORTED/recommendation.md
Add KB entry for Downgrade Mechanism Check.
=> Add KB entry for Downgrade Mechanism Check.

WEB_SERVICE/WEB/_HARDENING/WEB_HTTP_CSP/description.md
=> fix display

WEB_SERVICE/WEB/_MEDIUM/INSECURE_FORWARD_SECRECY/description.md, WEB_SERVICE/WEB/_MEDIUM/INSECURE_FORWARD_SECRECY/meta.json, WEB_SERVICE/WEB/_MEDIUM/INSECURE_FORWARD_SECRECY/recommendation.md
=> Insecure forward secrecy KB

WEB_SERVICE/DNS/_MEDIUM/DNS_TXT_RECORDS_MALICIOUS_CONTENT/description.md, WEB_SERVICE/DNS/_MEDIUM/DNS_TXT_RECORDS_MALICIOUS_CONTENT/meta.json, WEB_SERVICE/DNS/_MEDIUM/DNS_TXT_RECORDS_MALICIOUS_CONTENT/recommendation.md
Malicious Content (TXT Records) KB
=> Add DNS TXT Records Malicious Content KB

WEB_SERVICE/DNS/_HIGH/DNS_EMAIL_SECURITY_RECORDS/description.md, WEB_SERVICE/DNS/_HIGH/DNS_EMAIL_SECURITY_RECORDS/meta.json, WEB_SERVICE/DNS/_HIGH/DNS_EMAIL_SECURITY_RECORDS/recommendation.md
Add DNS email security records KB
=> Add DNS email security records KB

WEB_SERVICE/DNS/_MEDIUM/MTA_STS_MISCONFIGURATION/description.md, WEB_SERVICE/DNS/_MEDIUM/MTA_STS_MISCONFIGURATION/meta.json, WEB_SERVICE/DNS/_MEDIUM/MTA_STS_MISCONFIGURATION/recommendation.md
---
MTA-STS is a security protocol that enables mail servers to declare their ability to receive Transport Layer Security (TLS) secure SMTP connections. Misconfigurations in MTA-STS can compromise email security, lead to delivery failures, and expose organizations to downgrade attacks. The following areas are key concerns in MTA-STS configuration:
MTA-STS policies must be served over HTTPS and located at `.well-known/mta-sts.txt`. Common misconfigurations include:
* Incorrect MIME type (must be `text/plain`)
* Invalid syntax in the policy file
```bash
version: STSv1
mode: enforce
max_age: 604800
mx: mail.example.com
mx: backup-mail.example.com
```
The `_mta-sts` TXT record must be properly formatted. Misconfigurations include:
* Invalid record format
* Missing or incorrect version field …
=> Add misconfigured MTA-STS entry

.github/workflows/lint-pr.yml
This PR adds the semantic-pull-request GitHub Action to enforce Conventional Commits formatting for PR titles.
**Key Features**:
- Provides automated validation of PR titles
- Supports [WIP] prefix for work in progress
The action validates PR titles against patterns like: feat:, fix:, docs:, refactor:, test:, ci:, chore:
**Action**: https://github.com/amannn/action-semantic-pull-request
=> feature: Add semantic-pull-request GitHub Action `KB`

.mypy.ini, requirements.txt, tests/tools/kb_generator_test.py, tests/utils.py, tools/kb_generator.py
This PR introduces the following changes:
- Fixes mypy Errors.
- Update OpenAi module
- Switch from OpenAi To OpenRouter
=> fix: update openai & fix mypy

MOBILE_CLIENT/ANDROID/_HARDENING/APK_LIST_NOT_USED_PERMISSIONS/meta.json, MOBILE_CLIENT/ANDROID/_LOW/APK_TASK_HIJACKING/meta.json, MOBILE_CLIENT/ANDROID/_LOW/APK_USES_CLEAR_TEXT_TRAFFIC/meta.json, MOBILE_CLIENT/COMMON/_HARDENING/DEPRECATED_COMPONENT/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/BIOMETRIC_AUTHENTICATION_BYPASS/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_PASSWORD_STORAGE/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_STORAGE/meta.json, MOBILE_CLIENT/IOS/_LOW/UNSAFE_KEYCHAIN_ACCESSIBILITY/meta.json, MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_TAP/meta.json, MOBILE_CLIENT/IOS/_MEDIUM/IPA_URL_SCHEME_HIJACKING/meta.json
This PR builds on: https://github.com/Ostorlab/KB/pull/233 which adds only privacy issues related standards.
This PR adds the non privacy issues of the CNIL standard.
=> feature: non privacy issues in CNIL standards.

MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/meta.json, MOBILE_CLIENT/COMMON/_HIGH/INSECURE_JWT_SIGNATURE/meta.json, MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_ALGO/meta.json, MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_MODE/meta.json, MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_IV/meta.json, MOBILE_CLIENT/COMMON/_LOW/INSECURE_RANDOM_SEED/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/CRYPTO_INSECURE_CIPHER_KEY/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/WEAK_HASHING_ALGO/meta.json, MOBILE_CLIENT/IOS/_MEDIUM/IPA_INSECURE_TAP/meta.json
Based on different scans, this PR tries to rectify the mapping of kb entries to CNIL standards.
=> fix: improvements to CNIL standards

MOBILE_CLIENT/ANDROID/_HIGH/INSECURE_PACKAGE_CONTEXT/meta.json, MOBILE_CLIENT/COMMON/_HIGH/WIFI_API_PII/meta.json, MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/meta.json, MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_ALGO/meta.json, MOBILE_CLIENT/COMMON/_LOW/CRYPTO_INSECURE_CIPHER_MODE/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/INSECURE_STORAGE/meta.json, MOBILE_CLIENT/COMMON/_MEDIUM/LEAKING_PERSONAL_INFORMATION/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_ALIAS_LIMITING/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_ALIAS_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_ALIAS_LIMITING/recommendation.md
Mark GraphQL Alias Overloading as Secure  + remove failing URLs
=> feature: Secure graphql alias limiting

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_BATCH_LIMITING/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_BATCH_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_BATCH_LIMITING/recommendation.md
Mark GraphQL Array-Based Batch Queries as Secure
=> feature: Secure graphql batch limiting

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/recommendation.md
Add Secure KB for GraphQL Directive Overloading
=> feature: Secure graphql directive limiting

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/recommendation.md
Add Secure KB for GraphQL Field Duplication
=> feature: Secure graphql field duplication

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_CIRCULAR_REFERENCES/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_CIRCULAR_REFERENCES/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_CIRCULAR_REFERENCES/recommendation.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/recommendation.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/recommendation.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_HTTP_METHODS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_HTTP_METHODS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_HTTP_METHODS/recommendation.md
Add Secure KB for GraphQL Circular References
=> feature: Secure graphql circular references

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_OBJECT_LIMITS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_OBJECT_LIMITS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_OBJECT_LIMITS/recommendation.md
Add Secure KB for GraphQL Object Limit Protection
=> feature: Add Secure KB for GraphQL Object Limit Protection

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_TRACING/description.md , WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_TRACING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_TRACING/recommendation.md
Add Secure KB for GraphQL Tracing Protection
=> feature: Secure graphql tracing

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DEBUG_CONTROLS/description.md, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DEBUG_CONTROLS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DEBUG_CONTROLS/recommendation.md
Add Secure KB for GraphQL Debug Mode Protection
=> feature: Secure graphql debug controls

WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_ALIAS_BRUTEFORCING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_ALIAS_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_BATCH_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_CIRCULAR_FRAGMENTS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_CIRCULAR_REFERENCES/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DEBUG_CONTROLS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_DIRECTIVE_LIMITING/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_FIELD_DUPLICATION/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_HTTP_METHODS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_OBJECT_LIMITS/meta.json, WEB_SERVICE/WEB/_SECURE/SECURE_GRAPHQL_TRACING/meta.json
make new added graphql secure kbs have security issue set to true
=> fix: make new added graphql secure kbs have security issue set to true

MOBILE_CLIENT/COMMON/_CRITICAL/MALICIOUS_PACKAGE_COMOUTSYSTEMS_FILEVIEWER/context.md, MOBILE_CLIENT/COMMON/_CRITICAL/MALICIOUS_PACKAGE_COMOUTSYSTEMS_FILEVIEWER/description.md, MOBILE_CLIENT/COMMON/_CRITICAL/MALICIOUS_PACKAGE_COMOUTSYSTEMS_FILEVIEWER/meta.json, MOBILE_CLIENT/COMMON/_CRITICAL/MALICIOUS_PACKAGE_COMOUTSYSTEMS_FILEVIEWER/recommendation.md
Add KB Entry for Malicious Package: `com.outsystems.plugins.fileviewer`
=> feature: Add KB Entry for Malicious Package: `com.outsystems.plugins.fileviewer`

MOBILE_CLIENT/COMMON/_CRITICAL/MALICIOUS_PACKAGE_COMOUTSYSTEMS_FILEVIEWER/meta.json, WEB_SERVICE/TLS/_MEDIUM/TLS_BEAST_ATTACK/description.md, WEB_SERVICE/TLS/_MEDIUM/TLS_BEAST_ATTACK/meta.json, WEB_SERVICE/TLS/_MEDIUM/TLS_BEAST_ATTACK/recommendation.md
This vulnerability indicates that the server is susceptible to BEAST attacks, which exploit predictable initialization vectors in TLS 1.0 and SSL 3.0 CBC mode encryption to recover plaintext data through blockwise chosen boundary attacks.
BEAST (Browser Exploit Against SSL/TLS) occurs when TLS 1.0 or SSL 3.0 implementations use the last ciphertext block as the initialization vector for the next record, making encryption predictable. Attackers can exploit this through JavaScript-based chosen plaintext injection to guess secrets one byte at a time.
1. Attacker establishes man-in-the-middle position on network traffic
2. Malicious JavaScript injects chosen plaintext with controlled block boundaries
3. Predictable initialization vectors allow verification of guessed bytes
4. Gradual …
=> feature: TLS Beast Attack
